site_name: TorQ-FX
site_favicon: graphics/favicon.ico
pages:
    - Home: index.md
    - About: Overview.md
    - Getting Started: Installation.md
copyright: 'Copyright &copy 2016 AquaQ Analytics Limited.  Kx &reg and kdb+ are registered trademarks of Kx Systems Inc.'

theme: 'material'
repo_name: 'GitHub'
repo_url: 'https://github.com/AquaQAnalytics/TorQ-FX'
extra:
   logo: 'graphics/TorQ-logo.png' 
   palette:
      primary: 'indigo'
      accent: 'teal'
   social:
      - type: 'github'
        link: 'htps://github.com/AquaQAnalytics'
      - type: 'twitter'
        link: 'https://twitter.com/AquaQAnalytics'
      - type: 'linkedin'
        link: 'https://www.linkedin.com/company/aquaq-analytics'

google_analytics:
   - 'UA-51911331-4'
   - 'auto'
